# Generated by Django 4.1.7 on 2023-06-04 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TarefaColuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('posicao', models.IntegerField(verbose_name='Posição Coluna')),
                ('maximo_de_tarefas', models.IntegerField(blank=True, null=True, verbose_name='Número Máximo de Tarefas')),
                ('coluna_final', models.BooleanField(default=False, verbose_name='Coluna Final')),
                ('criado_em', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em')),
                ('alterado_em', models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
