# Generated by Django 4.1.7 on 2023-06-07 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500, verbose_name='Nome da Tarefa')),
                ('tempo', models.TimeField(verbose_name='Tempo da Tarefa')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição da Tarefa')),
                ('tarefa_coluna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.tarefacoluna')),
            ],
        ),
    ]
