# Generated by Django 4.1.7 on 2023-06-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='posicao',
            field=models.IntegerField(default=1, verbose_name='Posição Coluna'),
        ),
    ]
