# Generated by Django 4.1.7 on 2024-03-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_tarefa_posicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='nome',
            field=models.CharField(max_length=300, verbose_name='Nome da Tarefa'),
        ),
    ]
