# Generated by Django 4.1.7 on 2024-03-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_tarefa_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='descricao',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Descrição da Tarefa'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='tempo',
            field=models.TimeField(blank=True, null=True, verbose_name='Tempo da Tarefa'),
        ),
    ]
