# Generated by Django 4.1.7 on 2024-03-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_tarefa_descricao_alter_tarefa_tempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='alterado_em',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Alterado em'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='cor',
            field=models.CharField(blank=True, choices=[('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('red', 'Red'), ('cyan', 'Cyan'), ('orange', 'Orange'), ('purple', 'Purple'), ('magenta', 'Magenta')], max_length=10, null=True, verbose_name='Dia Da Semana'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
    ]
